development:
  adapter: postgresql
  database: my_winning_trade_development
  username: postgres
  port: <%= ENV['MYWINNINGTRADE_DB_1_PORT_5432_TCP_PORT'] %>
  host: <%= ENV['MYWINNINGTRADE_DB_1_PORT_5432_TCP_ADDR'] %>

test:
  adapter: postgresql
  database: my_winning_trade_test
  username: postgres
  port: <%= ENV['MYWINNINGTRADE_DB_1_PORT_5432_TCP_PORT'] %>
  host: <%= ENV['MYWINNINGTRADE_DB_1_PORT_5432_TCP_ADDR'] %>

production:
  adapter: postgresql
  database: my_winning_trade_development
  user: frank
  password: rockie123
  host: localhost
